---
- name: Setup CentOS timezone
  hosts: CentOS:Ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: set timezone to Europe/Helsinki
      timezone: name=Europe/Helsinki

- name: Setup windows timezone
  hosts: Windows
  gather_facts: no

  tasks:
    - name: set timezone to 'Finland Standard Time'
      win_timezone: timezone='E. Europe Standard Time'

# How to change time for ansible-server page.152
# Refer to pages 207 for windows